[package]
name = "hyper-ffi"
version = "0.1.0"
edition = "2024"

# fix for pixi + rattler-build
[workspace]

[lib]
crate-type = [
    "staticlib", # Ensure it gets compiled as a (static) C library
    "cdylib",    # If you want a shared/dynamic C library (advanced)
    "lib",       # For `generate-headers` and other downstream rust dependents
    #    "rlib",
    # such as integration `tests/`, doctests, and `examples/`
]


# hyper client
[[bin]]
name = "c01"
path = "examples/client/try01.rs"

[[bin]]
name = "c02"
path = "examples/client/try02.rs"

# hyper server
[[bin]]
name = "s01"
path = "examples/server/try01.rs"

[[bin]]
name = "s01b"
path = "examples/server/try01b.rs"

[[bin]]
name = "s01c"
path = "examples/server/try01c.rs"

[[bin]]
name = "s02"
path = "examples/server/try02.rs"


[dependencies]
safer-ffi = { git = "https://github.com/getditto/safer_ffi.git", features = [
    "python-headers",
] }

hyper = { version = "1", features = ["full"] }
tokio = { version = "1", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }

bytes = "1.2"
http = "1"
http-body = "1"


# Optional
serde = { version = "1", optional = true }
serde_json = { version = "1", optional = true }
pretty_env_logger = { version = "*", optional = true }
futures-channel = { version = "0.3", optional = true }
futures-util = { version = "0.3", default-features = false, optional = true }
h2 = { version = "0.4.2", optional = true }
httparse = { version = "1.9", optional = true }
httpdate = { version = "1.0", optional = true }
itoa = { version = "1", optional = true }
pin-project-lite = { version = "0.2.4", optional = true }
smallvec = { version = "1.12", features = [
    "const_generics",
    "const_new",
], optional = true }
tracing = { version = "0.1", default-features = false, features = [
    "std",
], optional = true }
want = { version = "0.3", optional = true }


[dev-dependencies]
form_urlencoded = "1"
futures-channel = { version = "0.3", features = ["sink"] }
futures-util = { version = "0.3", default-features = false, features = [
    "alloc",
    "sink",
] }

pretty_env_logger = "0.5"
pin-project-lite = "0.2.4"
spmc = "0.3"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

tokio-test = "0.4"
tokio-util = "0.7.10"


[features]
# Nothing by default
default = []

full = ["server", "client"]


#
# 添加可选依赖包
#
server = [
    "dep:serde_json",
    "dep:serde",
    "dep:httpdate",
    "dep:pin-project-lite",
    "dep:smallvec",
    "dep:pretty_env_logger",
    "dep:tracing",
    "dep:want",
]

# 可选依赖包
client = [
    "dep:serde_json",
    "dep:serde",
    "dep:httpdate",
    "dep:pin-project-lite",
    "dep:smallvec",
    "dep:pretty_env_logger",
    "dep:tracing",
    "dep:want",
]
