[package]
name = "hyper-ffi"
version = "0.1.0"
edition = "2024"

# fix for pixi + rattler-build
[workspace]

[lib]
crate-type = [
    "staticlib", # Ensure it gets compiled as a (static) C library
    "cdylib",    # If you want a shared/dynamic C library (advanced)
    "lib",       # For `generate-headers` and other downstream rust dependents
    #    "rlib",
    # such as integration `tests/`, doctests, and `examples/`
]


# hyper client
[[bin]]
name = "c01"
path = "examples/client/try01.rs"

# hyper server
[[bin]]
name = "s01"
path = "examples/server/try01.rs"


[dependencies]
safer-ffi = { git = "https://github.com/getditto/safer_ffi.git", features = [
    "python-headers",
] }

hyper = { version = "1", features = ["full"] }
tokio = { version = "1", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }

bytes = "1.2"
http = "1"
http-body = "1"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
pin-project-lite = "0.2"

[dev-dependencies]
form_urlencoded = "1"
futures-channel = { version = "0.3", features = ["sink"] }
futures-util = { version = "0.3", default-features = false, features = [
    "alloc",
    "sink",
] }

pretty_env_logger = "0.5"
pin-project-lite = "0.2.4"
spmc = "0.3"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

tokio-test = "0.4"
tokio-util = "0.7.10"


[features]
# Nothing by default
default = []

# Easily turn it all on
full = []
