version: "3"

tasks:
  magic:
    cmds:
      - magic {{.CLI_ARGS}}




  #
  # ref: https://taskfile.dev/usage/#looping-over-variables
  #
  publish:
    aliases: [ "up", "pub", "pub:auto" ]
    vars:
      UP_PKGS:
        sh: find . -name "*.conda" -type f
    cmds:
      - echo {{ .UP_PKGS }}
      - for: { var: UP_PKGS }
        cmd:
          |
          magic run rattler-build upload prefix -c "better-mojo" \
            --api-key=$PREFIX_DEV_API_KEY \
            {{.ITEM}}
      - open https://prefix.dev/channels/better-mojo
    dir: output/


  #
  # ref: https://taskfile.dev/usage/#looping-over-variables
  #
  publish:ffi:
    aliases: [ "upf", "pub", "pub:auto" ]
    vars:
      UP_PKGS:
        sh: find . -name "*.conda" -type f
    cmds:
      - echo $PREFIX_DEV_API_KEY
      - echo {{ .UP_PKGS }}
      - for: { var: UP_PKGS }
        cmd:
          |
          magic run rattler-build upload prefix -c "better-ffi" \
            --api-key=$PREFIX_DEV_API_KEY \
            {{.ITEM}}
      - open https://prefix.dev/channels/better-ffi
    dir: output/


  clean:
    aliases: [ "c", "cl" ]
    cmds:
      - rm -rf output/
