[project]
authors = ["hhglory <hhglory@outlook.com>"]
channels = [
    "https://repo.prefix.dev/better-ffi",
    "https://repo.prefix.dev/better-mojo",

    "https://conda.modular.com/max-nightly",
    "https://conda.modular.com/max",
    "https://repo.prefix.dev/modular-community",
    "conda-forge",
]
name = "try-uuid"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=25.2.0.dev2025022305,<26"


libuuid_ffi = ">=0.2.3,<0.3"
uuid = ">=0.2.3,<0.3"
