/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_UUID_FFI__
#define __RUST_UUID_FFI__
#ifdef __cplusplus
extern "C" {
#endif

/** \brief
 *  Frees a Rust-allocated string.
 */
void
free_rs_string (
    char * string);

/** \brief
 *  生成新的 UUIDv4
 */
char *
rs_uuid_v4 (void);

/** \brief
 *  生成新的 UUIDv4
 */
char *
rs_uuid_v7 (void);


#include <stddef.h>
#include <stdint.h>

typedef struct {
    uint8_t idx[16];
} uint8_16_array_t;

/** \brief
 *  格式化 UUID 为字符串
 */
char *
uuid_to_string (
    uint8_16_array_t const * bytes);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __RUST_UUID_FFI__ */
