/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_REDIS_FFI__
#define __RUST_REDIS_FFI__
#ifdef __cplusplus
extern "C" {
#endif

/** \brief
 *  释放 Rust 分配的字符串
 */
void
free_rs_string (
    char * string);

/** \brief
 *  关闭 Redis 连接
 */
void
redis_close (void);


#include <stddef.h>
#include <stdint.h>

/** \brief
 *  删除指定的键
 *
 *  # 参数
 *  - `key`: 键名
 *
 *  # 返回值
 *  - 成功删除的键数量
 */
int64_t
redis_del (
    char const * key);


#include <stdbool.h>

/** \brief
 *  检查键是否存在
 *
 *  # 参数
 *  - `key`: 键名
 *
 *  # 返回值
 *  - `true`: 键存在
 *  - `false`: 键不存在
 */
bool
redis_exists (
    char const * key);

/** \brief
 *  设置键的过期时间（秒）
 *
 *  # 参数
 *  - `key`: 键名
 *  - `seconds`: 过期时间（秒）
 *
 *  # 返回值
 *  - `true`: 设置成功
 *  - `false`: 设置失败
 */
bool
redis_expire (
    char const * key,
    int64_t seconds);

/** \brief
 *  获取字符串键值
 *
 *  # 参数
 *  - `key`: 键名
 *
 *  # 返回值
 *  - 成功: 返回键值字符串
 *  - 失败: 返回错误信息或 nil
 */
char *
redis_get (
    char const * key);

/** \brief
 *  删除哈希表字段
 *
 *  # 参数
 *  - `key`: 哈希表键名
 *  - `field`: 字段名
 *
 *  # 返回值
 *  - 成功删除的字段数量
 */
int64_t
redis_hdel (
    char const * key,
    char const * field);

/** \brief
 *  检查哈希表字段是否存在
 *
 *  # 参数
 *  - `key`: 哈希表键名
 *  - `field`: 字段名
 *
 *  # 返回值
 *  - `true`: 字段存在
 *  - `false`: 字段不存在
 */
bool
redis_hexists (
    char const * key,
    char const * field);

/** \brief
 *  获取哈希表字段值
 *
 *  # 参数
 *  - `key`: 哈希表键名
 *  - `field`: 字段名
 *
 *  # 返回值
 *  - 成功: 返回字段值
 *  - 字段不存在: 返回 "(nil)"
 *  - 失败: 返回错误信息
 */
char *
redis_hget (
    char const * key,
    char const * field);

/** \brief
 *  获取哈希表所有字段和值
 *
 *  # 参数
 *  - `key`: 哈希表键名
 *
 *  # 返回值
 *  - 成功: 返回 JSON 格式的字符串，如 {"field1":"value1","field2":"value2"}
 *  - 失败: 返回错误信息
 */
char *
redis_hgetall (
    char const * key);

/** \brief
 *  设置哈希表字段
 *
 *  # 参数
 *  - `key`: 哈希表键名
 *  - `field`: 字段名
 *  - `value`: 字段值
 *
 *  # 返回值
 *  - `true`: 设置成功
 *  - `false`: 设置失败
 */
bool
redis_hset (
    char const * key,
    char const * field,
    char const * value);

/** \brief
 *  初始化 Redis 连接
 *
 *  # 参数
 *  - `url`: Redis 连接 URL，格式如 "redis://127.0.0.1:6379/0"
 *
 *  # 返回值
 *  - `true`: 连接成功
 *  - `false`: 连接失败
 *
 *  # Safety
 *  - `url` 必须是有效的 UTF-8 字符串
 *  - 必须在程序启动时调用一次
 */
bool
redis_init (
    char const * url);

/** \brief
 *  检查 Redis 连接是否已初始化
 */
bool
redis_is_connected (void);

/** \brief
 *  获取列表长度
 *
 *  # 参数
 *  - `key`: 列表键名
 *
 *  # 返回值
 *  - 成功: 返回列表长度
 *  - 失败: 返回 -1
 */
int64_t
redis_llen (
    char const * key);

/** \brief
 *  从列表左侧弹出值
 *
 *  # 参数
 *  - `key`: 列表键名
 *
 *  # 返回值
 *  - 成功: 返回弹出的值
 *  - 列表为空: 返回 "(nil)"
 *  - 失败: 返回错误信息
 */
char *
redis_lpop (
    char const * key);

/** \brief
 *  将值推入列表左侧
 *
 *  # 参数
 *  - `key`: 列表键名
 *  - `value`: 要推入的值
 *
 *  # 返回值
 *  - 成功: 返回列表长度
 *  - 失败: 返回 -1
 */
int64_t
redis_lpush (
    char const * key,
    char const * value);

/** \brief
 *  执行 PING 命令，测试连接
 *
 *  # 返回值
 *  返回 "PONG" 如果连接正常，否则返回错误信息
 */
char *
redis_ping (void);

/** \brief
 *  执行原始 Redis 命令
 *
 *  # 参数
 *  - `cmd`: 命令名称
 *  - `args`: 命令参数，多个参数用空格分隔
 *
 *  # 返回值
 *  - 成功: 返回命令执行结果
 *  - 失败: 返回错误信息
 */
char *
redis_raw (
    char const * cmd,
    char const * args);

/** \brief
 *  从列表右侧弹出值
 *
 *  # 参数
 *  - `key`: 列表键名
 *
 *  # 返回值
 *  - 成功: 返回弹出的值
 *  - 列表为空: 返回 "(nil)"
 *  - 失败: 返回错误信息
 */
char *
redis_rpop (
    char const * key);

/** \brief
 *  将值推入列表右侧
 *
 *  # 参数
 *  - `key`: 列表键名
 *  - `value`: 要推入的值
 *
 *  # 返回值
 *  - 成功: 返回列表长度
 *  - 失败: 返回 -1
 */
int64_t
redis_rpush (
    char const * key,
    char const * value);

/** \brief
 *  将成员添加到集合
 *
 *  # 参数
 *  - `key`: 集合键名
 *  - `member`: 成员值
 *
 *  # 返回值
 *  - 成功: 返回添加到集合的元素数量（新元素为1，已存在为0）
 *  - 失败: 返回 -1
 */
int64_t
redis_sadd (
    char const * key,
    char const * member);

/** \brief
 *  获取集合成员数量
 *
 *  # 参数
 *  - `key`: 集合键名
 *
 *  # 返回值
 *  - 成功: 返回集合成员数量
 *  - 失败: 返回 -1
 */
int64_t
redis_scard (
    char const * key);

/** \brief
 *  设置字符串键值
 *
 *  # 参数
 *  - `key`: 键名
 *  - `value`: 键值
 *
 *  # 返回值
 *  - `true`: 设置成功
 *  - `false`: 设置失败
 */
bool
redis_set (
    char const * key,
    char const * value);

/** \brief
 *  检查成员是否在集合中
 *
 *  # 参数
 *  - `key`: 集合键名
 *  - `member`: 成员值
 *
 *  # 返回值
 *  - `true`: 成员存在
 *  - `false`: 成员不存在
 */
bool
redis_sismember (
    char const * key,
    char const * member);

/** \brief
 *  从集合移除成员
 *
 *  # 参数
 *  - `key`: 集合键名
 *  - `member`: 成员值
 *
 *  # 返回值
 *  - 成功: 返回从集合移除的元素数量
 *  - 失败: 返回 -1
 */
int64_t
redis_srem (
    char const * key,
    char const * member);

/** \brief
 *  获取键的剩余过期时间（秒）
 *
 *  # 参数
 *  - `key`: 键名
 *
 *  # 返回值
 *  - 成功: 返回剩余秒数
 *  - 键不存在或没有过期时间: 返回 -1
 *  - 错误: 返回 -2
 */
int64_t
redis_ttl (
    char const * key);

/** \brief
 *  获取库版本信息
 */
char *
redis_version (void);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __RUST_REDIS_FFI__ */
