[workspace]
authors = ["hhglory <hhglory@outlook.com>"]
channels = [
    "https://conda.modular.com/max-nightly",
    "conda-forge",
    "https://repo.prefix.dev/better-ffi",
]
name = "redis"
# platforms = ["osx-arm64"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]
version = "1.2.1"                                      # TODO X: 和 redis-rs 版本保持一致
preview = ["pixi-build"]


[package]
name = "redis"
version = "1.2.1"


[package.build]
backend = { name = "pixi-build-rattler-build", version = "*" }


[dependencies]
mojo = ">=1.0.0b2.dev2026052506,<2"

libredis_ffi = ">=1.2.1,<2"


[feature.dev.dependencies]
pre-commit = ">=4.2.0,<5"


[activation]
env = { MOJO_FLAGS = "-I . -I src" }


[environments]
default = { features = ["dev"], solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }


[tasks]
# Format
install-pre-commit = "pre-commit install"
format = { cmd = "mojo format src tests examples", depends-on = [
    "install-pre-commit",
] }
format-check = "mojo format --check src tests examples"


# Packaging
build-mojo = { cmd = "pixi run -e=dev rattler-build build --recipe recipes/mojo-recipe.yaml -c https://conda.modular.com/max -c conda-forge --skip-existing=all" }
build-rs = { cmd = "pixi run -e=dev rattler-build build --recipe recipes/rs-recipe.yaml -c https://conda.modular.com/max -c conda-forge --skip-existing=all" }
