[package]
name = "reqwest-ffi"
version = "0.1.0"
edition = "2024"


# fix for pixi + rattler-build
[workspace]

[lib]
crate-type = [
    "staticlib", # Ensure it gets compiled as a (static) C library
    "cdylib",    # If you want a shared/dynamic C library (advanced)
    "lib",       # For `generate-headers` and other downstream rust dependents
    #    "rlib",
    # such as integration `tests/`, doctests, and `examples/`
]


# http request
[[bin]]
name = "t01"
path = "examples/try01.rs"


[dependencies]
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
