[package]
name = "reqwest-ffi"
version = "0.1.0"
edition = "2024"


# fix for pixi + rattler-build
[workspace]

[lib]
crate-type = [
    "staticlib", # Ensure it gets compiled as a (static) C library
    "cdylib",    # If you want a shared/dynamic C library (advanced)
    "lib",       # For `generate-headers` and other downstream rust dependents
    #    "rlib",
    # such as integration `tests/`, doctests, and `examples/`
]


# http request
[[bin]]
name = "t01"
path = "examples/try01.rs"

[[bin]]
name = "t01b"
path = "examples/try01b.rs"

[[bin]]
name = "t02"
path = "examples/try02.rs"


[dependencies]
safer-ffi = { git = "https://github.com/getditto/safer_ffi.git", features = [
    "python-headers",
] }


reqwest = { version = "0.12", features = ["json", "blocking"] }
tokio = { version = "1", features = ["full"] }
