version: "3"

tasks:
  pixi:
    cmds:
      - pixi {{.CLI_ARGS}}

  cargo:
    cmds:
      - cargo {{.CLI_ARGS}}

  run:
    aliases: ["r"]
    cmds:
      - cargo run {{.CLI_ARGS}}

  gen:
    cmds:
      - cargo clean
      - cargo run generate-headers

  build:
    aliases: ["b"]
    cmds:
      - cargo test --features c-headers -- generate_headers
      - cargo build
      - open ../../target/debug
    ignore_error: true

  release:
    aliases: ["rel"]
    cmds:
      - cargo test --features c-headers -- generate_headers
      - cargo build --release
      - open ../../target/release
    ignore_error: true

  run:c:
    aliases: ["rc"]
    cmds:
      - task: b
      - gcc -L ./target/debug -l reqwest_ffi  -o main  main.c  -include stdio.h # 对应 libreqwest_ffi
      - ./main
      - rm -rf main
    ignore_error: true
